// Proves the published rules describe THIS system's actual behaviour.
//
// Two audiences, one script.
//
// For Head Quarter it is a staleness check: the rules endpoint ships vectors
// generated by running the validator, so if the validator changes and the
// vectors do not, something is caching or hand-editing them and the published
// contract has quietly stopped being true.
//
// For a publisher it is the reference implementation. Fetch /api/v1/content-rules,
// run every vector through your own validator, assert the verdicts match. A
// site that passes has PROVEN its validator agrees with HQ's, rather than
// having read a description of it. Copy this loop; the important part is that
// the expected answers come from HQ over the wire, not from a constant in your
// own repo — a constant is the second copy that drifts.
//
// Usage: tsx scripts/verify-content-rules.ts

import { buildContentRules } from "../lib/content-rules/registry";
import { validateGeneratedText } from "../lib/ai/validate";
import { measureVectors } from "../lib/content-rules/jsonld-rules";
import { proveFieldContractSensitivity } from "../lib/content-rules/field-contract";
import {
  runVectors,
  runScopeVectors,
  proveSupplyBridgeBranches,
  proveScopeBranches,
} from "../lib/content-rules/rendered-rules";
import type { FactSet } from "../lib/ai/facts";

async function main() {
  const rules = await buildContentRules();
  let passed = 0;
  const failures: string[] = [];

  console.log(`Luật nội dung phiên bản ${rules.version}\n`);

  // --- vectors ---
  for (const v of rules.rounding.vectors) {
    const factSet: FactSet = {
      vertical: "moving-services",
      zip: "00000",
      city: "Testville",
      state: "TX",
      county: "Example County",
      mainKeyword: null,
      countyKeyword: null,
        searchIntent: null,
      fingerprint: "vectors",
      facts: v.facts.map((f) => ({
        key: f.key,
        label: f.key,
        value: f.value,
        display: f.display,
        unit: f.unit,
        scope: f.scope as "ZIP" | "COUNTY" | "STATE",
        scopeName: f.scopeName,
      })),
    };
    const actual = validateGeneratedText(v.text, factSet).passed ? "accept" : "reject";
    const ok = actual === v.expect;
    if (ok) passed++;
    else failures.push(`vector "${v.text}" — công bố ${v.expect}, thực tế ${actual}`);
    console.log(`${ok ? "✓" : "✗"} [${v.expect}] ${v.text}`);
  }

  // --- the vectors must be able to disagree ---
  //
  // A conformance suite where every vector expects "accept" cannot detect a
  // validator that accepts everything. Checked explicitly, because that is
  // exactly the shape a suite decays into as rules loosen one at a time.
  const accepts = rules.rounding.vectors.filter((v) => v.expect === "accept").length;
  const rejects = rules.rounding.vectors.length - accepts;
  console.log();
  if (accepts > 0 && rejects > 0) {
    passed++;
    console.log(`✓ vector có cả hai chiều: ${accepts} chấp nhận, ${rejects} từ chối`);
  } else {
    failures.push(
      `vector chỉ có một chiều (${accepts} chấp nhận, ${rejects} từ chối) — một bộ vector không thể bất đồng thì không chứng minh được gì`
    );
    console.log(`✗ vector chỉ có một chiều`);
  }

  // --- vector JSON-LD: verdict công bố phải khớp verdict ĐO LẠI ---
  //
  // Cùng phép kiểm staleness mà `rounding.vectors` được hưởng, áp cho mục
  // `jsonLd` mới.
  //
  // NÓ BẮT ĐƯỢC GÌ, VÀ KHÔNG BẮT ĐƯỢC GÌ — vì cả hai vế chạy trong CÙNG tiến
  // trình, và một phép so hai thứ luôn bằng nhau là một phép không bao giờ đổ.
  //
  // KHÔNG bắt được: vị ngữ đổi hành vi. Nếu checkDisplayedOnlyValue đổi, cả
  // vector công bố lẫn vector đo lại đổi theo cùng nhau. Phép canh việc đó là
  // độ phủ nhánh trong scripts/verify-technical-rules.ts.
  //
  // BẮT ĐƯỢC: vector công bố ngừng đến từ việc CHẠY vị ngữ — ai đó thay lời gọi
  // bằng một bảng viết tay, hoặc cache một response cũ. Đó đúng chế độ hỏng mà
  // chú thích đầu file registry.ts mô tả ("something is caching or hand-editing
  // them"). Đã ép nổ một lần bằng đột biến 2026-09-10: sửa verdict của vector
  // đầu tiên thành "reject" thì phép này đổ, 11/12.
  //
  // Và đây là phép DUY NHẤT ở phía HQ. Phép thật nằm ở phía publisher: fetch
  // endpoint, chạy vector qua validator CỦA MÌNH, khẳng định verdict khớp —
  // hai tiến trình, hai bản cài đặt, nên chúng bất đồng được.
  const measured = measureVectors();
  const publishedJsonLd = rules.jsonLd.vectors;
  console.log();
  if (publishedJsonLd.length !== measured.length) {
    failures.push(`jsonLd.vectors công bố ${publishedJsonLd.length} vector, đo lại được ${measured.length}`);
    console.log(`✗ số vector JSON-LD không khớp`);
  } else {
    const drifted = publishedJsonLd.filter((v, i) => v.expect !== measured[i].expect || v.rule !== measured[i].rule);
    if (drifted.length === 0) {
      passed++;
      console.log(`✓ ${publishedJsonLd.length} vector JSON-LD: verdict công bố khớp verdict đo lại`);
    } else {
      failures.push(`${drifted.length} vector JSON-LD có verdict công bố khác verdict đo lại`);
      console.log(`✗ ${drifted.length} vector JSON-LD đã trôi lệch`);
    }
  }

  for (const rule of ["jsonld-value-displayed-only", "jsonld-aggregate-declares-scope"] as const) {
    const forRule = publishedJsonLd.filter((v) => v.rule === rule);
    const a = forRule.filter((v) => v.expect === "accept").length;
    const r = forRule.length - a;
    if (a > 0 && r > 0) {
      passed++;
      console.log(`✓ ${rule}: ${a} chấp nhận, ${r} từ chối`);
    } else {
      failures.push(`${rule}: vector chỉ có một chiều (${a} chấp nhận, ${r} từ chối)`);
      console.log(`✗ ${rule}: vector chỉ có một chiều`);
    }
  }

  // --- luật khai provenBy phải có vector mang tên nó ---
  //
  // Chỗ hở này KHÔNG phải giả thuyết: nó là chế độ hỏng mà cả hai phía đang
  // đếm bằng `provenBy`. Ai đó thêm một luật JSON-LD vào declaredRules, quên
  // thêm vector, và danh sách trông đầy đủ hơn thứ thật sự chạy được — đúng
  // câu chú thích ở đầu registry.ts cảnh báo.
  //
  // Phép "verdict công bố khớp verdict đo lại" ở trên KHÔNG bắt được nó: nó
  // duyệt các vector ĐANG CÓ, nên một luật không có vector nào thì nó không có
  // gì để duyệt và im lặng.
  //
  // Ép nổ bằng đột biến trước khi tin (2026-09-10): đổi id một luật thành tên
  // không có vector -> 13/14, dòng ✗ in ra đúng tên bịa.
  const jsonLdRuleIds = new Set<string>(rules.jsonLd.vectors.map((v) => v.rule));
  for (const d of rules.declaredRules.filter((r) => r.id.startsWith("jsonld-"))) {
    if (jsonLdRuleIds.has(d.id)) {
      passed++;
      console.log(`✓ ${d.id}: có vector mang đúng tên nó trong jsonLd.vectors`);
    } else {
      failures.push(`${d.id} khai provenBy nhưng jsonLd.vectors không có vector nào mang tên nó`);
      console.log(`✗ ${d.id}: khai có bằng chứng chạy, nhưng không vector nào mang tên nó`);
    }
  }

  // --- luật trên HTML đã render ---
  //
  // Chạy ở đây vì cả hai luật khai `provenBy: "HQ tự chạy"`. Một provenBy mà
  // không script nào thực thi là câu KHẲNG ĐỊNH về bằng chứng, không phải bằng
  // chứng — và tôi vừa viết đúng câu đó cho hai luật JSON-LD một giờ trước,
  // nên nó không phải rủi ro giả định.
  //
  // Kiểm CẢ ba thứ, vì chúng hỏng theo ba cách khác nhau:
  //   verdict khớp        -> vị ngữ còn phân loại đúng
  //   cả hai chiều        -> bộ vector còn bất đồng được
  //   nhánh còn ép nổ     -> nhánh thu hẹp chưa chết
  //
  // Cái thứ ba là cái hai cái đầu KHÔNG bắt được: một nhánh chết vẫn để mọi
  // vector xanh, vì các ca còn lại vẫn phân loại đúng nhờ nhánh khác.
  const renderedSuites = [
    { id: "rendered-supply-side-bridge", vectors: runVectors(), proofs: proveSupplyBridgeBranches() },
    { id: "cluster-scope-count-mismatch", vectors: runScopeVectors(), proofs: proveScopeBranches() },
  ];
  console.log();
  for (const suite of renderedSuites) {
    const bad = suite.vectors.filter((v) => !v.ok);
    const accepts = suite.vectors.filter((v) => v.expect === "accept").length;
    const rejects = suite.vectors.length - accepts;

    if (bad.length === 0 && accepts > 0 && rejects > 0) {
      passed++;
      console.log(`✓ ${suite.id}: ${suite.vectors.length} vector khớp (${accepts} accept / ${rejects} reject)`);
    } else {
      failures.push(
        bad.length > 0
          ? `${suite.id}: ${bad.length} vector lệch verdict`
          : `${suite.id}: vector chỉ có một chiều (${accepts} accept / ${rejects} reject)`
      );
      console.log(`✗ ${suite.id}: ${bad.length} lệch, ${accepts} accept / ${rejects} reject`);
    }

    const dead = suite.proofs.filter((p) => p.vectorsChanged === 0);
    if (dead.length === 0) {
      passed++;
      console.log(
        `✓ ${suite.id}: ${suite.proofs.length} nhánh đều ép nổ được — ` +
          suite.proofs.map((p) => `${p.branch}:${p.vectorsChanged}`).join(", ")
      );
    } else {
      failures.push(
        `${suite.id}: nhánh ${dead.map((d) => d.branch).join(", ")} không ca nào ép nổ được — ` +
          `xoá nhánh đi mà bộ vector vẫn xanh thì nó không canh gì`
      );
      console.log(`✗ ${suite.id}: nhánh chết — ${dead.map((d) => d.branch).join(", ")}`);
    }
  }

  // --- fieldContract: băm phải NHẠY và phải CÔ LẬP ---
  const sens = proveFieldContractSensitivity(rules.fieldContract);
  const brokenFields = sens.filter((p) => !p.isolated);
  console.log();
  if (brokenFields.length === 0) {
    passed++;
    console.log(`✓ fieldContract: ${Object.keys(rules.fieldContract).length} băm, mỗi băm nhạy với đầu vào của nó và không trùng nhau`);
  } else {
    for (const b of brokenFields) failures.push(`fieldContract.${b.field}: ${b.detail}`);
    console.log(`✗ fieldContract: ${brokenFields.map((b) => `${b.field} (${b.detail})`).join("; ")}`);
  }

  // --- metric resolutions ---
  const ambiguous = rules.metricResolutions.filter((m) => m.ambiguous);
  if (rules.metricResolutions.length === 0) {
    // KHÔNG tính là đạt. Với database rỗng — cổng PR, một checkout sạch —
    // phép này không có gì để soi, và "✓ 0 chỉ số, mỗi chỉ số đúng một
    // resolution" là một câu ĐÚNG nói về tập rỗng. Nó đọc y hệt một phép kiểm
    // vừa xác nhận điều gì đó.
    //
    // Đo 2026-09-10 trên Postgres rỗng vừa migrate: 9/10 phép ở đây vẫn kiểm
    // thật (8 vector chạy qua validator thật, cộng phép đòi vector có cả hai
    // chiều) vì chúng dùng fact tổng hợp. Chỉ phép này là rỗng.
    console.log(`— chỉ số: KHÔNG KẾT LUẬN ĐƯỢC (database không có DataPoint nào)`);
    console.log(`  Không phải đạt, cũng không phải trượt — không có dữ liệu để hỏi.`);
  } else if (ambiguous.length === 0) {
    passed++;
    console.log(`✓ ${rules.metricResolutions.length} chỉ số, mỗi chỉ số đúng một resolution`);
  } else {
    // Not a failure of this script — a fact about the data that any site
    // summing these metrics must be told, loudly, before it sums them.
    console.log(`⚠ ${ambiguous.length} chỉ số có NHIỀU resolution — site cộng gộp phải xử lý riêng:`);
    for (const m of ambiguous) console.log(`   ${m.metric}: ${m.resolutions.join(", ")}`);
    passed++;
  }

  const nonZip = rules.metricResolutions.filter((m) => !m.resolutions.includes("ZIP"));
  console.log(
    `\n${nonZip.length}/${rules.metricResolutions.length} chỉ số KHÔNG đo ở cấp ZIP — cộng theo từng ZIP sẽ nhân lên:`
  );
  for (const m of nonZip) console.log(`   ${m.metric.padEnd(48)} ${m.resolutions.join(",")}`);

  // Luật chưa có bằng chứng nào chạy được là luật chưa ai thấy nổ. Đếm ra
  // thay vì để danh sách trông đầy đủ — một luật khai báo mà không nơi nào
  // chứng minh nó chạy thì đọc y hệt một luật đang bảo vệ điều gì đó.
  const unproven = rules.declaredRules.filter((d) => !d.provenBy);
  console.log(`\nLuật khai báo: ${rules.declaredRules.length}, trong đó ${unproven.length} CHƯA có bằng chứng chạy được:`);
  for (const d of unproven) console.log(`   ${d.id}`);

  console.log(`\nTerm dành riêng: ${rules.reservedTerms.length}`);
  for (const t of rules.reservedTerms) console.log(`   "${t.term}" -> ${t.ownedBy}`);

  // Tổng đếm theo số phép THẬT SỰ hỏi được, không theo số phép có mặt trong
  // file. Trên database rỗng, phép chỉ số không hỏi được gì nên nó rời khỏi cả
  // tử số lẫn mẫu số — nếu chỉ rời tử số thì kết quả thành 9/10 và trông như
  // một phép vừa TRƯỢT.
  // +3: một phép staleness cho vector JSON-LD, và một phép hai-chiều cho mỗi
  // trong hai luật JSON-LD.
  // Mẫu số đếm theo số phép THẬT SỰ chạy, không theo hằng số viết tay. Một
  // hằng số ở đây là bản sao thứ hai của "có bao nhiêu phép", và nó trôi lệch
  // ngay lần đầu ai đó thêm luật JSON-LD thứ ba: phép mới chạy, tử số tăng,
  // mẫu số đứng yên, và kết quả in ra 13/12.
  const jsonLdDeclared = rules.declaredRules.filter((r) => r.id.startsWith("jsonld-")).length;
  const total =
    rules.rounding.vectors.length +
    1 + // vector làm tròn có cả hai chiều
    1 + // verdict công bố khớp verdict đo lại
    jsonLdDeclared * 2 + // mỗi luật: cả hai chiều, và có vector mang tên nó
    renderedSuites.length * 2 + // mỗi luật render: vector khớp, và mọi nhánh ép nổ được
    1 + // fieldContract: băm nhạy và cô lập
    (rules.metricResolutions.length === 0 ? 0 : 1);
  console.log(`\n${passed}/${total} kiểm tra đúng.`);
  if (failures.length > 0) {
    console.error(`\nTHẤT BẠI:\n  ${failures.join("\n  ")}`);
    process.exitCode = 1;
  }
}

main();
