// Proves the published rules describe THIS system's actual behaviour.
//
// Two audiences, one script.
//
// For Head Quarter it is a staleness check: the rules endpoint ships vectors
// generated by running the validator, so if the validator changes and the
// vectors do not, something is caching or hand-editing them and the published
// contract has quietly stopped being true.
//
// For a publisher it is the reference implementation. Fetch /api/v1/content-rules,
// run every vector through your own validator, assert the verdicts match. A
// site that passes has PROVEN its validator agrees with HQ's, rather than
// having read a description of it. Copy this loop; the important part is that
// the expected answers come from HQ over the wire, not from a constant in your
// own repo — a constant is the second copy that drifts.
//
// Usage: tsx scripts/verify-content-rules.ts

import { buildContentRules } from "../lib/content-rules/registry";
import { measureVectors } from "../lib/content-rules/jsonld-rules";
import { validateGeneratedText } from "../lib/ai/validate";
import type { FactSet } from "../lib/ai/facts";

async function main() {
  const rules = await buildContentRules();
  let passed = 0;
  const failures: string[] = [];

  console.log(`Luật nội dung phiên bản ${rules.version}\n`);

  // --- vectors ---
  for (const v of rules.rounding.vectors) {
    const factSet: FactSet = {
      vertical: "moving-services",
      zip: "00000",
      city: "Testville",
      state: "TX",
      county: "Example County",
      mainKeyword: null,
      countyKeyword: null,
      fingerprint: "vectors",
      facts: v.facts.map((f) => ({
        key: f.key,
        label: f.key,
        value: f.value,
        display: f.display,
        unit: f.unit,
        scope: f.scope as "ZIP" | "COUNTY" | "STATE",
        scopeName: f.scopeName,
      })),
    };
    const actual = validateGeneratedText(v.text, factSet).passed ? "accept" : "reject";
    const ok = actual === v.expect;
    if (ok) passed++;
    else failures.push(`vector "${v.text}" — công bố ${v.expect}, thực tế ${actual}`);
    console.log(`${ok ? "✓" : "✗"} [${v.expect}] ${v.text}`);
  }

  // --- JSON-LD vectors ---
  //
  // Chạy ở đây vì registry vừa khai `provenBy: "HQ tự chạy: measureVectors()"`.
  // Một provenBy mà không script nào thực thi là một câu khẳng định về bằng
  // chứng, không phải bằng chứng — và nó đọc y hệt bằng chứng thật.
  //
  // measureVectors() ĐO verdict bằng cách gọi checkDisplayedOnlyValue /
  // checkAggregateTechnique, không đọc một hằng số. Nên nếu vị ngữ đổi mà
  // vector không đổi, chỗ này lệch chứ không im.
  const jsonld = measureVectors();
  const jsonldByRule = new Map<string, { accept: number; reject: number }>();
  for (const v of jsonld) {
    const entry = jsonldByRule.get(v.rule) ?? { accept: 0, reject: 0 };
    if (v.expect === "accept") entry.accept++;
    else entry.reject++;
    jsonldByRule.set(v.rule, entry);
  }
  console.log();
  for (const [rule, c] of jsonldByRule) {
    const bothWays = c.accept > 0 && c.reject > 0;
    if (bothWays) {
      passed++;
      console.log(`✓ ${rule}: ${c.accept} chấp nhận, ${c.reject} từ chối — vector có cả hai chiều`);
    } else {
      failures.push(`${rule} chỉ có một chiều (${c.accept} chấp nhận, ${c.reject} từ chối)`);
      console.log(`✗ ${rule} chỉ có một chiều`);
    }
  }

  // Mọi luật khai `HQ tự chạy` phải có mặt trong số vừa đo. Nếu ai đó thêm một
  // luật JSON-LD vào registry mà quên thêm vector, chỗ này nói ra — thay vì để
  // danh sách declaredRules trông đầy đủ hơn thứ thật sự chạy được.
  const claimsSelfRun = rules.declaredRules.filter((d) => d.id.startsWith("jsonld-"));
  for (const d of claimsSelfRun) {
    if (jsonldByRule.has(d.id)) passed++;
    else {
      failures.push(`${d.id} khai provenBy nhưng measureVectors() không sinh vector nào cho nó`);
      console.log(`✗ ${d.id}: khai có bằng chứng chạy, nhưng không vector nào mang tên nó`);
    }
  }

  // --- the vectors must be able to disagree ---
  //
  // A conformance suite where every vector expects "accept" cannot detect a
  // validator that accepts everything. Checked explicitly, because that is
  // exactly the shape a suite decays into as rules loosen one at a time.
  const accepts = rules.rounding.vectors.filter((v) => v.expect === "accept").length;
  const rejects = rules.rounding.vectors.length - accepts;
  console.log();
  if (accepts > 0 && rejects > 0) {
    passed++;
    console.log(`✓ vector có cả hai chiều: ${accepts} chấp nhận, ${rejects} từ chối`);
  } else {
    failures.push(
      `vector chỉ có một chiều (${accepts} chấp nhận, ${rejects} từ chối) — một bộ vector không thể bất đồng thì không chứng minh được gì`
    );
    console.log(`✗ vector chỉ có một chiều`);
  }

  // --- metric resolutions ---
  const ambiguous = rules.metricResolutions.filter((m) => m.ambiguous);
  if (rules.metricResolutions.length === 0) {
    // KHÔNG tính là đạt. Với database rỗng — cổng PR, một checkout sạch —
    // phép này không có gì để soi, và "✓ 0 chỉ số, mỗi chỉ số đúng một
    // resolution" là một câu ĐÚNG nói về tập rỗng. Nó đọc y hệt một phép kiểm
    // vừa xác nhận điều gì đó.
    //
    // Đo 2026-09-10 trên Postgres rỗng vừa migrate: 9/10 phép ở đây vẫn kiểm
    // thật (8 vector chạy qua validator thật, cộng phép đòi vector có cả hai
    // chiều) vì chúng dùng fact tổng hợp. Chỉ phép này là rỗng.
    console.log(`— chỉ số: KHÔNG KẾT LUẬN ĐƯỢC (database không có DataPoint nào)`);
    console.log(`  Không phải đạt, cũng không phải trượt — không có dữ liệu để hỏi.`);
  } else if (ambiguous.length === 0) {
    passed++;
    console.log(`✓ ${rules.metricResolutions.length} chỉ số, mỗi chỉ số đúng một resolution`);
  } else {
    // Not a failure of this script — a fact about the data that any site
    // summing these metrics must be told, loudly, before it sums them.
    console.log(`⚠ ${ambiguous.length} chỉ số có NHIỀU resolution — site cộng gộp phải xử lý riêng:`);
    for (const m of ambiguous) console.log(`   ${m.metric}: ${m.resolutions.join(", ")}`);
    passed++;
  }

  const nonZip = rules.metricResolutions.filter((m) => !m.resolutions.includes("ZIP"));
  console.log(
    `\n${nonZip.length}/${rules.metricResolutions.length} chỉ số KHÔNG đo ở cấp ZIP — cộng theo từng ZIP sẽ nhân lên:`
  );
  for (const m of nonZip) console.log(`   ${m.metric.padEnd(48)} ${m.resolutions.join(",")}`);

  // Luật chưa có bằng chứng nào chạy được là luật chưa ai thấy nổ. Đếm ra
  // thay vì để danh sách trông đầy đủ — một luật khai báo mà không nơi nào
  // chứng minh nó chạy thì đọc y hệt một luật đang bảo vệ điều gì đó.
  const unproven = rules.declaredRules.filter((d) => !d.provenBy);
  console.log(`\nLuật khai báo: ${rules.declaredRules.length}, trong đó ${unproven.length} CHƯA có bằng chứng chạy được:`);
  for (const d of unproven) console.log(`   ${d.id}`);

  console.log(`\nTerm dành riêng: ${rules.reservedTerms.length}`);
  for (const t of rules.reservedTerms) console.log(`   "${t.term}" -> ${t.ownedBy}`);

  // Tổng đếm theo số phép THẬT SỰ hỏi được, không theo số phép có mặt trong
  // file. Trên database rỗng, phép chỉ số không hỏi được gì nên nó rời khỏi cả
  // tử số lẫn mẫu số — nếu chỉ rời tử số thì kết quả thành 9/10 và trông như
  // một phép vừa TRƯỢT.
  const total =
    rules.rounding.vectors.length +
    1 +
    (rules.metricResolutions.length === 0 ? 0 : 1) +
    jsonldByRule.size +
    claimsSelfRun.length;
  console.log(`\n${passed}/${total} kiểm tra đúng.`);
  if (failures.length > 0) {
    console.error(`\nTHẤT BẠI:\n  ${failures.join("\n  ")}`);
    process.exitCode = 1;
  }
}

main();
