// Proves the published rules describe THIS system's actual behaviour.
//
// Two audiences, one script.
//
// For Head Quarter it is a staleness check: the rules endpoint ships vectors
// generated by running the validator, so if the validator changes and the
// vectors do not, something is caching or hand-editing them and the published
// contract has quietly stopped being true.
//
// For a publisher it is the reference implementation. Fetch /api/v1/content-rules,
// run every vector through your own validator, assert the verdicts match. A
// site that passes has PROVEN its validator agrees with HQ's, rather than
// having read a description of it. Copy this loop; the important part is that
// the expected answers come from HQ over the wire, not from a constant in your
// own repo — a constant is the second copy that drifts.
//
// Usage: tsx scripts/verify-content-rules.ts

import { buildContentRules } from "../lib/content-rules/registry";
import { validateGeneratedText } from "../lib/ai/validate";
import type { FactSet } from "../lib/ai/facts";

async function main() {
  const rules = await buildContentRules();
  let passed = 0;
  const failures: string[] = [];

  console.log(`Luật nội dung phiên bản ${rules.version}\n`);

  // --- vectors ---
  for (const v of rules.rounding.vectors) {
    const factSet: FactSet = {
      vertical: "moving-services",
      zip: "00000",
      city: "Testville",
      state: "TX",
      county: "Example County",
      mainKeyword: null,
      countyKeyword: null,
      fingerprint: "vectors",
      facts: v.facts.map((f) => ({
        key: f.key,
        label: f.key,
        value: f.value,
        display: f.display,
        unit: f.unit,
        scope: f.scope as "ZIP" | "COUNTY" | "STATE",
        scopeName: f.scopeName,
      })),
    };
    const actual = validateGeneratedText(v.text, factSet).passed ? "accept" : "reject";
    const ok = actual === v.expect;
    if (ok) passed++;
    else failures.push(`vector "${v.text}" — công bố ${v.expect}, thực tế ${actual}`);
    console.log(`${ok ? "✓" : "✗"} [${v.expect}] ${v.text}`);
  }

  // --- the vectors must be able to disagree ---
  //
  // A conformance suite where every vector expects "accept" cannot detect a
  // validator that accepts everything. Checked explicitly, because that is
  // exactly the shape a suite decays into as rules loosen one at a time.
  const accepts = rules.rounding.vectors.filter((v) => v.expect === "accept").length;
  const rejects = rules.rounding.vectors.length - accepts;
  console.log();
  if (accepts > 0 && rejects > 0) {
    passed++;
    console.log(`✓ vector có cả hai chiều: ${accepts} chấp nhận, ${rejects} từ chối`);
  } else {
    failures.push(
      `vector chỉ có một chiều (${accepts} chấp nhận, ${rejects} từ chối) — một bộ vector không thể bất đồng thì không chứng minh được gì`
    );
    console.log(`✗ vector chỉ có một chiều`);
  }

  // --- metric resolutions ---
  const ambiguous = rules.metricResolutions.filter((m) => m.ambiguous);
  if (ambiguous.length === 0) {
    passed++;
    console.log(`✓ ${rules.metricResolutions.length} chỉ số, mỗi chỉ số đúng một resolution`);
  } else {
    // Not a failure of this script — a fact about the data that any site
    // summing these metrics must be told, loudly, before it sums them.
    console.log(`⚠ ${ambiguous.length} chỉ số có NHIỀU resolution — site cộng gộp phải xử lý riêng:`);
    for (const m of ambiguous) console.log(`   ${m.metric}: ${m.resolutions.join(", ")}`);
    passed++;
  }

  const nonZip = rules.metricResolutions.filter((m) => !m.resolutions.includes("ZIP"));
  console.log(
    `\n${nonZip.length}/${rules.metricResolutions.length} chỉ số KHÔNG đo ở cấp ZIP — cộng theo từng ZIP sẽ nhân lên:`
  );
  for (const m of nonZip) console.log(`   ${m.metric.padEnd(48)} ${m.resolutions.join(",")}`);

  console.log(`\nTerm dành riêng: ${rules.reservedTerms.length}`);
  for (const t of rules.reservedTerms) console.log(`   "${t.term}" -> ${t.ownedBy}`);

  const total = rules.rounding.vectors.length + 2;
  console.log(`\n${passed}/${total} kiểm tra đúng.`);
  if (failures.length > 0) {
    console.error(`\nTHẤT BẠI:\n  ${failures.join("\n  ")}`);
    process.exitCode = 1;
  }
}

main();
